### ISSUE TITLE
PDAL info with --boundary close on nitf returns segfault

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#1024]
Example: `pdal info --stats --filters.stats.enumerate=Classification --boundary --pointcloudschema /tmp/schema_293145N0650400E_20110402140109_HALOE_020_PC3_00_0_UFO.ntf.xml --metadata /u02/LASdata/griddata/HALOE/20110402_00_0_UFO/PC3/293145N0650400E_20110402140109_HALOE_020_PC3_00_0_UFO.ntf`

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe9713c8a in std::vector<hexer::Path*, std::allocator<hexer::Path*> >::size (this=0x31)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_vector.h:655
655	      { return size_type(this->_M_impl._M_finish - this->_M_impl._M_start); }
```

```
(gdb) bt
#0  0x00007fffe9713c8a in std::vector<hexer::Path*, std::allocator<hexer::Path*> >::size (this=0x31)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_vector.h:655
#1  0x00007fffe9711fd1 in hexer::Path::~Path (this=0x21, __in_chrg=<value optimized out>) at /home/gridusr/local/include/hexer/Path.hpp:45
#2  0x00007fffe9712279 in hexer::HexGrid::~HexGrid (this=0x268dd10, __in_chrg=<value optimized out>)
    at /home/gridusr/local/include/hexer/HexGrid.hpp:46
#3  0x00007fffe971609c in std::default_delete<hexer::HexGrid>::operator() (this=0x63f6a0, __ptr=0x268dd10)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
#4  0x00007fffe9714049 in std::unique_ptr<hexer::HexGrid, std::default_delete<hexer::HexGrid> >::~unique_ptr (this=0x63f6a0,
    __in_chrg=<value optimized out>) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
#5  0x00007fffe971c7be in pdal::HexBin::~HexBin (this=0x63f610, __in_chrg=<value optimized out>)
    at /home/gridusr/local/src/PDAL/plugins/hexbin/filters/HexBin.hpp:46
#6  0x00007fffe971c7fa in pdal::HexBin::~HexBin (this=0x63f610, __in_chrg=<value optimized out>)
    at /home/gridusr/local/src/PDAL/plugins/hexbin/filters/HexBin.hpp:46
#7  0x000000000041b66c in std::default_delete<pdal::Stage>::operator() (this=0x63e580, __ptr=0x63f610)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
#8  0x000000000041a52b in std::unique_ptr<pdal::Stage, std::default_delete<pdal::Stage> >::~unique_ptr (this=0x63e580,
    __in_chrg=<value optimized out>) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
#9  0x000000000041ea38 in std::_Destroy<std::unique_ptr<pdal::Stage> > (__pointer=0x63e580)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_construct.h:93
#10 0x000000000041dd2d in std::_Destroy_aux<false>::__destroy<std::unique_ptr<pdal::Stage>*> (__first=0x63e580, __last=0x63e588)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_construct.h:103
#11 0x000000000041cc37 in std::_Destroy<std::unique_ptr<pdal::Stage>*> (__first=0x63e570, __last=0x63e588)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_construct.h:126
#12 0x000000000041b4ad in std::_Destroy<std::unique_ptr<pdal::Stage>*, std::unique_ptr<pdal::Stage> > (__first=0x63e570, __last=0x63e588)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_construct.h:151
#13 0x000000000041a1c7 in std::vector<std::unique_ptr<pdal::Stage, std::default_delete<pdal::Stage> >, std::allocator<std::unique_ptr<pdal::Stage, std::default_delete<pdal::Stage> > > >::~vector (this=0x638be8, __in_chrg=<value optimized out>)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/stl_vector.h:424
#14 0x00007ffff7babf7e in pdal::PipelineManager::~PipelineManager (this=0x638b90, __in_chrg=<value optimized out>)
    at /home/gridusr/local/src/PDAL/include/pdal/PipelineManager.hpp:48
#15 0x00007ffff7babfce in std::default_delete<pdal::PipelineManager>::operator() (this=0x633a30, __ptr=0x638b90)
---Type <return> to continue, or q <return> to quit---
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
#16 0x00007ffff7babcb5 in std::unique_ptr<pdal::PipelineManager, std::default_delete<pdal::PipelineManager> >::~unique_ptr (this=0x633a30,
    __in_chrg=<value optimized out>) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
#17 0x00007ffff7ccee6e in pdal::InfoKernel::~InfoKernel (this=0x6337a0, __in_chrg=<value optimized out>)
    at /home/gridusr/local/src/PDAL/kernels/info/InfoKernel.hpp:58
#18 0x00007ffff7ccef3a in pdal::InfoKernel::~InfoKernel (this=0x6337a0, __in_chrg=<value optimized out>)
    at /home/gridusr/local/src/PDAL/kernels/info/InfoKernel.hpp:58
#19 0x000000000041b986 in std::default_delete<pdal::Kernel>::operator() (this=0x7fffffffdeb0, __ptr=0x6337a0)
    at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:76
#20 0x000000000041a907 in std::unique_ptr<pdal::Kernel, std::default_delete<pdal::Kernel> >::~unique_ptr (this=0x7fffffffdeb0,
    __in_chrg=<value optimized out>) at /opt/rh/devtoolset-3/root/usr/include/c++/4.9.2/bits/unique_ptr.h:236
#21 0x0000000000418910 in main (argc=7, argv=0x7fffffffe208) at /home/gridusr/local/src/PDAL/apps/pdal.cpp:246
```

**Comment by hobu** [comment]
No segfault on OSX...

**Comment by hobu** [comment]
No segfault on Linux with master

**Comment by msmitherdc** [comment]
I was getting these on master. Used the grid vm to replicate.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Howard ButlerSent: Monday, November 2, 2015 9:54 AMTo: PDAL/PDALReply To: PDAL/PDALCc: Michael D. SmithSubject: Re: [PDAL] PDAL info with --boundary close on nitf returns segfault (#1024)No segfault on Linux with master

—Reply to this email directly or view it on GitHub.

**Comment by msmitherdc** [comment]
After completely deleting the hexer and pdal repos and rebuilding, issue is gone.
