### ISSUE TITLE
filters.crop with multiple polygons gives "Missing ',' or ']' in array declaration"

### ISSUE THREAD

**Issue by ludvikbrodl** [PDAL/PDAL#2281]
I'm trying to filter on several polygons using the crop filter. But validation fails when I specify a list of polygons instead of a singe polygon. I could not find a ready example of the exact syntax to use for multiple polygons so I used the one example of the bounds attribute for crop and tried to apply it to polygon. [Link to the referred Example](https://pdal.io/pipeline.html#point-views-and-multiple-outputs)

My pipeline looks as follows:

```
{
    "pipeline": [
        {
            "type": "readers.las",
            "filename": "18D022_67450_5775_25.laz"
        },
        {
            "type": "filters.crop",
            "polygon":
                [ "POLYGON ((580133.332641037 6745738.20288874,580142.119915551 6745749.09658287,580146.008257756 6745753.91927777,580154.615420594 6745764.59726109,580186.473348476 6745735.89900483,580171.969703082 6745719.26115816,580157.071647402 6745731.77279894,580153.696473688 6745727.58557315,580149.242670236 6745730.98400633,580146.380167014 6745727.45454043,580133.332641037 6745738.20288874))", "POLYGON ((580046.957227278 6745874.90101861,580052.218908005 6745881.28088126,580052.811853235 6745881.996132,580103.523963947 6745840.29459308,580097.6696138 6745833.18826031,580046.957227278 6745874.90101861))", "POLYGON ((579930.10707073 6745981.50321912,579933.510167111 6745985.65743483,579934.758244876 6745988.4374562,579936.011255865 6745991.2398724,579936.395856376 6745994.45735127,579936.749155154 6745997.37329818,579936.292504172 6746000.03710638,579935.45556391 6746003.17148839,579931.557843857 6746007.74139972,579946.747220439 6746019.73635621,579953.402668222 6746010.51529578,579945.840002697 6746004.90847844,579946.907123779 6745995.87407327,579949.534827569 6745993.6266313,579946.415216799 6745983.8632579,579939.915657006 6745973.27759827,579930.10707073 6745981.50321912))", "POLYGON ((579885.183882405 6746046.27790156,579892.038643492 6746054.84360325,579934.353017146 6746021.06288149,579927.498036475 6746012.50823481,579885.183882405 6746046.27790156))", "POLYGON ((579869.869881062 6746031.10498873,579876.379696435 6746039.29524938,579906.011731646 6746015.81484561,579899.507371662 6746007.62465271,579869.869881062 6746031.10498873))" ]
        },
        {
          "type": "writers.text",
          "format": "csv",
          "filename": "buildings-buffered.las"
        }
    ]
}
```
It starts processing but after a few seconds I get the error:

```
Traceback (most recent call last):
  File "script_many.py", line 150, in <module>
    main()
  File "script_many.py", line 146, in main
    processFile(su.infile, su.outfile)
  File "script_many.py", line 113, in processFile
    pipeline_buffered_buildings.validate()
  File "/home/a002166/miniconda2/envs/pdal-env/lib/python3.6/site-packages/pdal/pipeline.py", line 43, in validate
    return self.p.validate()
  File "pdal/libpdalpython.pyx", line 182, in pdal.libpdalpython.PyPipeline.validate
RuntimeError: JSON pipeline: Unable to parse pipeline:
* Line 10, Column 23
  Missing ',' or ']' in array declaration
```
Using pdal 1.8 installed via conda

(I've looked at the json for an hour without seeing any syntax error, my apologies if this is an error on my part)

**Comment by abellgithub** [comment]
This parses fine when not going through the python interface.  I'll look more later.

**Comment by abellgithub** [comment]
Can you try your pipeline with the command-line interface to see what happens?

**Comment by ludvikbrodl** [comment]
It worked out fine when running with the command-line.

**Comment by ludvikbrodl** [comment]
There must be an error on my side. I just ran the pipeline by opening the json file with open("pipe.json", "r") as f: f.read() and it ran just fine. The output in my OP is from a print() and must be malformed somehow, will search further tomorrow.

**Comment by ludvikbrodl** [comment]
I can not for the life of me figure out what is causing the issue, but I worked around it by using a dict and them using json.dumps(). Which is the better approach. The first time around I wrote a json string directly in the source code and used replace for the polygons, which was a product of me not understanding the documentation of filters.crop: polygon (no example on how to specify many polygons)

The error can be reproduced by using the follow code snippet:
fill `polygons` with WKT strings of polygons!
```
    polygons = [] # Fill this array with WKT strings
    polygons_string = ""
    for poly in polygons:
        polygons_string += '"' + poly + '",'
    polygons_string = polygons_string[:-1]  # throw away ","
    json_string = pipeline_template.replace("__POLYGONS__", polygons_string)
    print(json_string)
    with open("json_from_script.json", "w") as f:
        f.write(json_string)
    pipeline_buildings = pdal.Pipeline(json_string)
    pipeline_buildings.validate()
    pipeline_buildings.execute()
    print("Done with buildings points")
```
The very weird part is that if you run the pipeline with the json that is saved to disk from this script, the pipeline parses fine without the 
```
  File "/home/a002166/miniconda2/envs/pdal-env/lib/python3.6/site-packages/pdal/pipeline.py", line 43, in validate
    return self.p.validate()
  File "pdal/libpdalpython.pyx", line 182, in pdal.libpdalpython.PyPipeline.validate
RuntimeError: JSON pipeline: Unable to parse pipeline:
* Line 10, Column 23
  Missing ',' or ']' in array declaration
```
Since if found a way to work around this I will not search further unless asked by you. 

Versions that is used to reproduce this error:
```
$ pip freeze
appdirs==1.4.3
attrs==18.2.0
black==18.9b0
certifi==2018.10.15
Click==7.0
GDAL==2.3.2
mkl-fft==1.0.6
mkl-random==1.0.2
numpy==1.15.0
packaging==18.0
PDAL==2.1.8
pyparsing==2.3.0
six==1.11.0
toml==0.10.0
```
python version: 3.6.7

**Comment by hobu** [comment]
Sorry you're having so much trouble. This post was helpful. This is the PDAL Python's fault. I think what is going on is the PDAL Python extension is mucking with your JSON on the way in. It does the following:

https://github.com/PDAL/python/blob/master/pdal/libpdalpython.pyx#L118

```
self.thisptr = new Pipeline(json.encode('UTF-8'), c_arrays)
```

Note the encoding to UTF-8 there. I wonder if your data is already in another encoding that is lossy when going to UTF-8. I'll try to get a reproducible conda environment going here.

**Comment by abellgithub** [comment]
I think the best way to debug is to create a test case that fails when passed a string literal to the API, such as:

```
json_string = """{
    "pipeline": [
        {
            "type": "readers.las",
            "filename": "18D022_67450_5775_25.laz"
        },
        {
            "type": "filters.crop",
            "polygon":
                [ ... ]
        }
    ]
}""" 

pdal.Pipeline(json_string)

```

where the `...` in the polygon key is replaced by text that is valid but causes the failure.

**Comment by hobu** [comment]
The following scenario succeeds for me in Python using conda on osx:

```
#!/usr/bin/env python

pipeline="""{
  "pipeline":[
    "/Users/hobu/dev/git/pdal/test/data/las/1.2-with-color.las",
    {
      "type":"filters.crop",
      "polygon":
       [ "POLYGON ((580133.332641037 6745738.20288874,580142.119915551 6745749.09658287,580146.008257756 6745753.91927777,580154.615420594 6745764.59726109,580186.473348476 6745735.89900483,580171.969703082 6745719.26115816,580157.071647402 6745731.77279894,580153.696473688 6745727.58557315,580149.242670236 6745730.98400633,580146.380167014 6745727.45454043,580133.332641037 6745738.20288874))", "POLYGON ((580046.957227278 6745874.90101861,580052.218908005 6745881.28088126,580052.811853235 6745881.996132,580103.523963947 6745840.29459308,580097.6696138 6745833.18826031,580046.957227278 6745874.90101861))", "POLYGON ((579930.10707073 6745981.50321912,579933.510167111 6745985.65743483,579934.758244876 6745988.4374562,579936.011255865 6745991.2398724,579936.395856376 6745994.45735127,579936.749155154 6745997.37329818,579936.292504172 6746000.03710638,579935.45556391 6746003.17148839,579931.557843857 6746007.74139972,579946.747220439 6746019.73635621,579953.402668222 6746010.51529578,579945.840002697 6746004.90847844,579946.907123779 6745995.87407327,579949.534827569 6745993.6266313,579946.415216799 6745983.8632579,579939.915657006 6745973.27759827,579930.10707073 6745981.50321912))", "POLYGON ((579885.183882405 6746046.27790156,579892.038643492 6746054.84360325,579934.353017146 6746021.06288149,579927.498036475 6746012.50823481,579885.183882405 6746046.27790156))", "POLYGON ((579869.869881062 6746031.10498873,579876.379696435 6746039.29524938,579906.011731646 6746015.81484561,579899.507371662 6746007.62465271,579869.869881062 6746031.10498873))" ],
      "outside":false
    },
    {
      "filename":"crop-wkt.las",
      "compression":false
    }
  ]
}
"""

import pdal
p = pdal.Pipeline(pipeline)
p.validate()
p.execute()
```

I wonder if there's a locale issue. What does the following print for you when you run it in python?
```
import locale
locale.setlocale(locale.LC_ALL, "")
message_language = locale.getlocale(locale.LC_MESSAGES)[0]
print (message_language)
```

**Comment by ludvikbrodl** [comment]
```
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_ALL, "")
'en_GB.UTF-8'
>>> message_language = locale.getlocale(locale.LC_MESSAGES)[0]
>>> print (message_language)
en_GB
```

**Comment by abellgithub** [comment]
I think @ludvikbrodl needs to reproduce with a static string or we should close.

**Comment by hobu** [comment]
I believe his strings above produce the issue for him in his environment, but when I run them, they do not behave similarly in my environment. Another approach might be to attempt to replicate in Docker so we are all working from the same base.

**Comment by abellgithub** [comment]
There's no static string in the ticket, just strings generated from code.

**Comment by ludvikbrodl** [comment]
look again @ https://github.com/PDAL/PDAL/issues/2281#issuecomment-441959651
The first code block

**Comment by abellgithub** [comment]
What is the exact command/process you're using to have the pipeline processed that results in failure?

**Comment by ludvikbrodl** [comment]
...Wow.

There was a programming error on my part. Noticed now when I was producing a complete test script for you. I had an incorrectly formatted json:
```{
    "pipeline": [
        {
            "type": "readers.las",
            "filename": "buildings-cropped.las"
        },
        {
            "type": "filters.crop",
            "polygon":
ERROR HERE -->  [ ": "POLYGON ((580133.332641037 6745738.20288874,580142.119915551 6745749.09658287,580146.008257756 6745753.91927777,580154.615420594 6745764.59726109,580186.473348476 6745735.89900483,580171.969703082 6745719.26115816,580157.071647402 6745731.77279894,580153.696473688 6745727.58557315,580149.242670236 6745730.98400633,580146.380167014 6745727.45454043,580133.332641037 6745738.20288874))" ]
        },
        {
          "type": "writers.text",
          "format": "csv",
          "filename": "buildings-buffered.csv"
        }
    ]
}

[ "POLYGON ((580133.332641037 6745738.20288874,580142.119915551 6745749.09658287,580146.008257756 6745753.91927777,580154.615420594 6745764.59726109,580186.473348476 6745735.89900483,580171.969703082 6745719.26115816,580157.071647402 6745731.77279894,580153.696473688 6745727.58557315,580149.242670236 6745730.98400633,580146.380167014 6745727.45454043,580133.332641037 6745738.20288874))"]
```

I am very sorry for leading you on a goose chase.
