### ISSUE TITLE
How to set scale as 0.00000001

### ISSUE THREAD

**Issue by muyanchen-zen** [PDAL/PDAL#3040]
```c++
                const double scale = 0.000001; //precision=6
                Options options;
                options.add("filename", file_name);
                options.add("minor_version", 4);
                //x->options.add("precision", 10);
                options.add("scale_x", scale);
                options.add("scale_y", scale);
                options.add("scale_z", scale);
```
When i tried to set precision as 0.00000001 , the program turned out to be segment fault. 
How to fix it to 0.00000001 ?

**Comment by abellgithub** [comment]
I can think of no reason why the specific value you've provided would cause a segmentation fault.  Can you provide a traceback?

**Comment by muyanchen-zen** [comment]
It's not a segment fault, sorry for my wrong memorize.
the abort is 
```sh
terminate called after throwing an instance of 'pdal::pdal_error'
  what():  writers.las: Unable to convert scaled value (6.018137e+11) to int32 for dimension 'Z' when writing LAS/LAZ file test.las.
Aborted (core dumped)
```
It can be traced back to file "io/LasWriter.cpp" line 917.
```sh
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fab02a7d801 in __GI_abort () at abort.c:79
#2  0x00007fab03470957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fab03476ae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fab03476b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fab03476d54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fab045a45e2 in pdal::Stage::throwError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /usr/local/lib/libpdal_base.so.9
#7  0x00007fab0448832b in pdal::LasWriter::fillPointBuf(pdal::PointRef&, pdal::LeInserter&)::{lambda(double, pdal::Dimension::Id)#1}::operator()(double, pdal::Dimension::Id) const () from /usr/local/lib/libpdal_base.so.9
#8  0x00007fab0448871d in pdal::LasWriter::fillPointBuf(pdal::PointRef&, pdal::LeInserter&) () from /usr/local/lib/libpdal_base.so.9
#9  0x00007fab04488d85 in pdal::LasWriter::fillWriteBuf(pdal::PointView const&, unsigned long, std::vector<char, std::allocator<char> >&) ()
   from /usr/local/lib/libpdal_base.so.9
#10 0x00007fab044873c8 in pdal::LasWriter::writeView(std::shared_ptr<pdal::PointView>) () from /usr/local/lib/libpdal_base.so.9
#11 0x00007fab043f019c in pdal::FlexWriter::write(std::shared_ptr<pdal::PointView>) () from /usr/local/lib/libpdal_base.so.9
#12 0x00007fab043ef791 in pdal::Writer::run(std::shared_ptr<pdal::PointView>) () from /usr/local/lib/libpdal_base.so.9
#13 0x00007fab045aad01 in pdal::StageRunner::run() () from /usr/local/lib/libpdal_base.so.9
#14 0x00007fab045a3316 in pdal::Stage::execute(pdal::BasePointTable&, std::set<std::shared_ptr<pdal::PointView>, pdal::PointViewLess, std::allocator<std::shared_ptr<pdal::PointView> > >&) () from /usr/local/lib/libpdal_base.so.9
#15 0x00007fab045a2d37 in pdal::Stage::execute(pdal::BasePointTable&) () from /usr/local/lib/libpdal_base.so.9
#16 0x000055869f7a24d5 in main (argc=1, argv=0x7ffc83d78f98) at /home/workspace/PDAL-2.0.1-src/examples/writing/writer.cpp:192

```

**Comment by abellgithub** [comment]
The issue is as described by the error.  The value you're trying to write is too large to fit into 32 bits with the precision you've requested.  This is a limitation of the LAS format, which writes X, Y and Z values using 32 bits of precision.  If you increase the scale factor (make it less precise), you should have no problem.
