### ISSUE TITLE
filter.DBSCAN not working properly with other dimensions

### ISSUE THREAD

**Issue by guemilgm** [PDAL/PDAL#3243]
**Describe the bug**
Issue:
When running **filters.dbscan** with other dimensions except for **"dimensions":"X,Y,Z"** the command runs for a while and throws a memory error (after around 6-7 minutes of processing one LAS file). I tried to run the command using "dimensions":"Z" and I got the behavior before described.

The error message is follows:
**--- Sample_000390 ---
Traceback (most recent call last):
  File "C:/Users/guemi/AppData/Roaming/JetBrains/PyCharmCE2020.2/scratches/scratch_12.py", line 79, in <module>
    count = p.execute()
  File "C:\Users\guemi\anaconda3\envs\env_pdal2_2\lib\site-packages\pdal\pipeline.py", line 40, in execute
    return self.p.execute()
  File "libpdalpython.pyx", line 166, in pdal.libpdalpython.PyPipeline.execute
MemoryError: bad allocation
[Sample_000390.zip](https://github.com/PDAL/PDAL/files/5229381/Sample_000390.zip)

Process finished with exit code 1**

```
$ pdal translate in.las out.las
```

<details>
  
```
"pipeline":[
            {
                "type":"filters.dbscan",
                "min_points":10,
                "eps":2.0,
                "dimensions":"Z"
            },
            {
                "type":"filters.range",
                "limits":"ClusterID![-1:-1],Classification[26:26]"
            },
            {
                "type":"filters.ferry",
                "dimensions":"ClusterID => PointSourceId"
            },
            {
                "type":"writers.las",
                "filename":"%s"
            }
          ]```

</details>

**Expected behavior**
Obtain a segmented LAS file ONLY the Z dimension (or another dimension)

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
$ uname -a
```

```
$ pdal --version
```

If installed via Conda, you may be asked to paste the output of `conda list` and `conda info` as well.

<details>
  
```
$ conda list
```
# packages in environment at C:\Users\guemi\anaconda3\envs\env_pdal2_2:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.74.0               hd4e6614_0    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.7.22                     0
cairo                     1.16.0            hc79e3cf_1005    conda-forge
certifi                   2020.6.20                py38_0
cfitsio                   3.470                hbbe6aef_6    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
curl                      7.71.1               h4b64cdc_5    conda-forge
expat                     2.2.9                h33f27b4_2    conda-forge
freetype                  2.10.2               hd328e21_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      3.1.2            py38h5f218aa_1    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.6.0                h09e6dc1_1    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.66.0               h31c07e1_0    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
icu                       67.1                 h33f27b4_0    conda-forge
intel-openmp              2020.1                      216
jpeg                      9d                   he774522_0    conda-forge
jsoncpp                   1.8.4             h1ad3211_1002    conda-forge
kealib                    1.4.13               h3b59ab9_1    conda-forge
krb5                      1.17.1               hc04afaa_3    conda-forge
laszip                    3.4.3                h6538335_1    conda-forge
laz-perf                  1.4.4                ha925a31_0    conda-forge
libblas                   3.8.0                    16_mkl    conda-forge
libcblas                  3.8.0                    16_mkl    conda-forge
libcurl                   7.71.1               h4b64cdc_5    conda-forge
libffi                    3.2.1             ha925a31_1007    conda-forge
libgdal                   3.1.2                h586bd2e_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             he9e54da_1012    conda-forge
liblapack                 3.8.0                    16_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_105    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
libpq                     12.3                 hd9aa61d_0    conda-forge
libspatialite             4.3.0a            h9ed2f40_1039    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
mkl                       2020.1                      216
msys2-conda-epoch         20160418                      1
nitro                     2.7.dev6             h33f27b4_3    conda-forge
numpy                     1.19.1           py38h72c728b_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1g               he774522_1
pandas                    1.1.1            py38ha925a31_0    anaconda
pcre                      8.44                 h6538335_0    conda-forge
pdal                      2.2.0                h5d0705d_0    conda-forge
pip                       20.2.3                     py_0    conda-forge
pixman                    0.38.0            hfa6e2cd_1003    conda-forge
poppler                   0.89.0               h5d62644_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.3                 he14cc48_0    conda-forge
powershell_shortcut       0.0.1                         3
proj                      7.1.0                h7d85306_1    conda-forge
python                    3.8.5           h60c2a47_7_cpython    conda-forge
python-dateutil           2.8.1                      py_0    anaconda
python-pdal               2.3.4            py38h6a11f7f_3    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                     py_0    anaconda
setuptools                49.6.0           py38h32f6830_0    conda-forge
six                       1.15.0                     py_0    anaconda
sqlite                    3.33.0               he774522_0    conda-forge
tbb                       2020.1               he980bc4_0    conda-forge
tiledb                    2.0.8                h71c485d_0    conda-forge
tk                        8.6.10               he774522_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
whitebox                  1.4.0                      py_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
xerces-c                  3.2.3                ha925a31_1    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zlib                      1.2.11            h62dcd97_1009    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge
</details>

<details>
  
```
$ conda info
```
active environment : env_pdal2_2
    active env location : C:\Users\guemi\anaconda3\envs\env_pdal2_2
            shell level : 1
       user config file : C:\Users\guemi\.condarc
 populated config files : C:\Users\guemi\.condarc
          conda version : 4.8.4
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\guemi\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\guemi\anaconda3\pkgs
                          C:\Users\guemi\.conda\pkgs
                          C:\Users\guemi\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\guemi\anaconda3\envs
                          C:\Users\guemi\.conda\envs
                          C:\Users\guemi\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
</details>

**Comment by abellgithub** [comment]
I can't recreate this. You will have to provide data in order to allow it to be researched further.

**Comment by chambbj** [comment]
My initial thought here is that you've got potentially a couple of problems. First, by limiting to a single dimension, the neighborhoods arising from the "radius" searches end up being quite dense. I didn't compute any statistics, but with the "radius" (`eps` parameter) I'd guess that your neighborhoods have thousands if not tens of thousands of points, imposing quite a bit of computational complexity. On top of that, we actually precompute and stash these neighborhoods to reduce the number of searches later in the code. My guess is that this is where you are blowing up. Maybe you'd have better luck by reducing the radius. Are you also sure you want to use only the Z dimension?

**Comment by guemilgm** [comment]
Hi Andrew,
I attached a LAS file along with my message. I dragged a dropped the file
as the Github site suggested.
Is there any other way to provide data?

Miguel

**Comment by abellgithub** [comment]
I missed the data in the original message. Is this resolved for you by altering parameters or your expectations of behavior?

**Comment by guemilgm** [comment]
Hi Andrew,
I am glad you found the data.
DBSCAN only works for me when I use the combination "X,Y,Z" dimensions,
nothing else. If I tried to use one dimension out of that combination (e.i.
Z) or another dimension, the command doesn't not work.

**Comment by abellgithub** [comment]
Did you read comment left by @chambbj above?

**Comment by guemilgm** [comment]
Thanks for your comment.
Your explanation makes sense to me now. I thought that by only using one
dimension the process would run faster.
Say I want to segment the data by the Scattering dimension, would you
recommend using "X, Y, Scattering"?

Thanks again for your help

Miguel

**Comment by chambbj** [comment]
It will segment on the dimensions you provide. Whether or not those are the correct dimensions for your application are up to you to determine. "X,Y,Scattering" will still incorporate the spatial dimensions of X and Y, as well as Scattering.

**Comment by guemilgm** [comment]
I will try that for this dataset. However, I tried that before and I did
not get any result.
I will keep you updated.

Thanks!

Miguel

**Comment by hobu** [comment]
Please reopen if there still is an issue here.
