### ISSUE TITLE
Fedora 34: pdal_io_bpf_base_test: Exception: SegFault

### ISSUE THREAD

**Issue by neteler** [PDAL/PDAL#3261]
**Describe the bug**

I am the maintainer of PDAL on Fedora and try to push PDAL 2.1.0 to Fedora 34.
Doing so, I got this error:

https://kojipkgs.fedoraproject.org//work/tasks/5399/53305399/build.log

```
...
27/107 Test  #30: pdal_io_bpf_zlib_test ..................   Passed    0.17 sec
        Start  33: pdal_io_ept_addon_writer_test
 28/107 Test  #28: pdal_zstd_test .........................   Passed    0.28 sec
        Start  34: pdal_io_faux_test
 29/107 Test  #27: pdal_deflate_test ......................   Passed    0.37 sec
        Start  35: pdal_io_gdal_reader_test
 30/107 Test  #34: pdal_io_faux_test ......................   Passed    0.11 sec
        Start  36: pdal_io_gdal_writer_test
 31/107 Test  #29: pdal_io_bpf_base_test ..................***Exception: SegFault  0.49 sec
[==========] Running 15 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 15 tests from BpfTestBase
[ RUN      ] BpfTestBase.test_point_major
[       OK ] BpfTestBase.test_point_major (17 ms)
[ RUN      ] BpfTestBase.test_dim_major
[       OK ] BpfTestBase.test_dim_major (4 ms)
[ RUN      ] BpfTestBase.test_byte_major
[       OK ] BpfTestBase.test_byte_major (25 ms)
[ RUN      ] BpfTestBase.roundtrip_byte
        Start  37: pdal_io_las_reader_test
 32/107 Test  #36: pdal_io_gdal_writer_test ...............   Passed    0.22 sec
        Start  38: pdal_io_las_writer_test
 33/107 Test  #35: pdal_io_gdal_reader_test ...............   Passed    0.83 sec
        Start  39: pdal_io_optech_test
...

106/107 Test  #55: pdal_filters_colorization_test .........   Passed    6.21 sec
107/107 Test #103: translate_test .........................   Passed    3.53 sec
99% tests passed, 1 tests failed out of 107
Total Test time (real) =  11.72 sec
The following tests FAILED:
	 29 - pdal_io_bpf_base_test (SEGFAULT)
Errors while running CTest
error: Bad exit status from /var/tmp/rpm-tmp.OX4doa (%check)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.OX4doa (%check)
Child return code was: 1
EXCEPTION: [Error()]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.8/site-packages/mockbuild/util.py", line 789, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/PDAL.spec
```

I am not sure how to provide more detailed information about the failing test.

Note that no such problem occurred with Fedora 32 and 33:
https://src.fedoraproject.org/rpms/PDAL

**Expected behavior**

The compilation runs without error.

**System/installation information:**

- PDAL 2.1.0
- Fedora 34
- PDAL SPEC file: https://src.fedoraproject.org/rpms/PDAL/tree/master

**Comment by abellgithub** [comment]
Can you run the test directly and get a traceback?

**Comment by neteler** [comment]
I have now run everything in a Fedora 34 docker container:

```
docker pull fedora:34
...
dnf update -y
dnf install wget rpm-build -y
cd ~
wget https://kojipkgs.fedoraproject.org//work/tasks/5374/53305374/PDAL-2.1.0-9.fc34.src.rpm
rpm -Uhv PDAL-2.1.0-9.fc34.src.rpm
cd ~/rpmbuild/SPECS/
dnf install 'dnf-command(builddep)' -y
dnf builddep PDAL.spec
rpmbuild -ba PDAL.spec
```

Interestingly, this time a different test error occurred:

```
+ cd /root/rpmbuild/BUILD
+ cd PDAL-2.1.0-src
+ cd x86_64-redhat-linux-gnu
+ /usr/bin/ctest --output-on-failure --force-new-ctest-process -j8
Test project /root/rpmbuild/BUILD/PDAL-2.1.0-src/x86_64-redhat-linux-gnu
        Start   1: pdal_bounds_test
        Start   2: pdal_config_test
        Start   3: pdal_eigen_test
        Start   4: pdal_file_utils_test
        Start   5: pdal_georeference_test
        Start   6: pdal_kdindex_test
        Start   7: pdal_kernel_test
        Start   8: pdal_log_test
  1/107 Test   #4: pdal_file_utils_test ...................   Passed    0.69 sec
        Start   9: pdal_metadata_test
  2/107 Test   #6: pdal_kdindex_test ......................   Passed    0.68 sec
        Start  10: pdal_oldpclblock_test
  3/107 Test   #2: pdal_config_test .......................   Passed    0.69 sec

...
  
 73/107 Test  #79: pdal_filters_reprojection_test .........   Passed    0.15 sec
        Start  81: pdal_filters_randomize_test
 74/107 Test  #38: pdal_io_las_writer_test ................***Failed    1.60 sec
[==========] Running 27 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 27 tests from LasWriterTest
[ RUN      ] LasWriterTest.srs
[       OK ] LasWriterTest.srs (21 ms)
[ RUN      ] LasWriterTest.srs2
[       OK ] LasWriterTest.srs2 (5 ms)
[ RUN      ] LasWriterTest.auto_offset
[       OK ] LasWriterTest.auto_offset (2 ms)
[ RUN      ] LasWriterTest.auto_offset2
[       OK ] LasWriterTest.auto_offset2 (3 ms)
[ RUN      ] LasWriterTest.extra_dims
[       OK ] LasWriterTest.extra_dims (4 ms)
[ RUN      ] LasWriterTest.all_extra_dims
[       OK ] LasWriterTest.all_extra_dims (7 ms)
[ RUN      ] LasWriterTest.forward
(readers.las Error) GDAL failure (1) PROJ: proj_create_from_database: crs not found
(readers.las Error) GDAL failure (1) PROJ: proj_create_from_database: crs not found
[       OK ] LasWriterTest.forward (361 ms)
[ RUN      ] LasWriterTest.forwardvlr
proj_uom_get_info_from_database: unit of measure not found
[       OK ] LasWriterTest.forwardvlr (25 ms)
[ RUN      ] LasWriterTest.flex
[       OK ] LasWriterTest.flex (6 ms)
[ RUN      ] LasWriterTest.flex2
[       OK ] LasWriterTest.flex2 (2 ms)
[ RUN      ] LasWriterTest.laszip
[       OK ] LasWriterTest.laszip (210 ms)
[ RUN      ] LasWriterTest.laszip1_4
[       OK ] LasWriterTest.laszip1_4 (268 ms)
[ RUN      ] LasWriterTest.flex_vlr
[       OK ] LasWriterTest.flex_vlr (22 ms)
[ RUN      ] LasWriterTest.stream
[       OK ] LasWriterTest.stream (176 ms)
[ RUN      ] LasWriterTest.streamhashwrite
[       OK ] LasWriterTest.streamhashwrite (14 ms)
[ RUN      ] LasWriterTest.fix1063_1064_1065
[       OK ] LasWriterTest.fix1063_1064_1065 (107 ms)
[ RUN      ] LasWriterTest.pdal_metadata
[       OK ] LasWriterTest.pdal_metadata (2 ms)
[ RUN      ] LasWriterTest.pdal_add_vlr
[       OK ] LasWriterTest.pdal_add_vlr (2 ms)
[ RUN      ] LasWriterTest.issue2937
[       OK ] LasWriterTest.issue2937 (185 ms)
[ RUN      ] LasWriterTest.badVlr
[       OK ] LasWriterTest.badVlr (2 ms)
[ RUN      ] LasWriterTest.evlroffset
[       OK ] LasWriterTest.evlroffset (1 ms)
[ RUN      ] LasWriterTest.forward_spec_3
[       OK ] LasWriterTest.forward_spec_3 (4 ms)
[ RUN      ] LasWriterTest.oversize_vlr
[       OK ] LasWriterTest.oversize_vlr (1 ms)
[ RUN      ] LasWriterTest.issue1940
[       OK ] LasWriterTest.issue1940 (0 ms)
[ RUN      ] LasWriterTest.issue2663
/root/rpmbuild/BUILD/PDAL-2.1.0-src/test/unit/io/LasWriterTest.cpp:1496: Failure
Expected equality of these values:
  h.scaleX()
    Which is: 1e-07
  .001
    Which is: 0.001
/root/rpmbuild/BUILD/PDAL-2.1.0-src/test/unit/io/LasWriterTest.cpp:1497: Failure
Expected equality of these values:
  h.scaleY()
    Which is: 1e-07
  .001
    Which is: 0.001
/root/rpmbuild/BUILD/PDAL-2.1.0-src/test/unit/io/LasWriterTest.cpp:1498: Failure
Expected equality of these values:
  h.scaleZ()
    Which is: 0.01
  .001
    Which is: 0.001
[  FAILED  ] LasWriterTest.issue2663 (75 ms)
[ RUN      ] LasWriterTest.issue2320
[       OK ] LasWriterTest.issue2320 (7 ms)
[ RUN      ] LasWriterTest.synthetic_points
[       OK ] LasWriterTest.synthetic_points (2 ms)
[----------] 27 tests from LasWriterTest (1514 ms total)

[----------] Global test environment tear-down
[==========] 27 tests from 1 test suite ran. (1514 ms total)
[  PASSED  ] 26 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LasWriterTest.issue2663

 1 FAILED TEST

        Start  82: pdal_filters_reciprocity_test
 75/107 Test  #80: pdal_filters_range_test ................   Passed    0.09 sec
        Start  83: pdal_filters_returns_test
 76/107 Test  #33: pdal_io_ept_addon_writer_test ..........   Passed    1.71 sec
        Start  84: pdal_filters_shell_test
 77/107 Test  #81: pdal_filters_randomize_test ............   Passed    0.10 sec
        Start  85: pdal_filters_skewness_test
 78/107 Test  #77: pdal_filters_overlay_test ..............   Passed    0.29 sec
        Start  86: pdal_filters_smrf_test
 79/107 Test  #82: pdal_filters_reciprocity_test ..........   Passed    0.07 sec
        Start  87: pdal_filters_sort_test
 80/107 Test  #83: pdal_filters_returns_test ..............   Passed    0.12 sec
        Start  88: pdal_filters_splitter_test
 81/107 Test  #86: pdal_filters_smrf_test .................   Passed    0.07 sec
        Start  89: pdal_filters_stats_test
 82/107 Test  #89: pdal_filters_stats_test ................   Passed    0.07 sec
        Start  90: pdal_filters_transformation_test
 83/107 Test  #90: pdal_filters_transformation_test .......   Passed    0.08 sec
        Start  91: pdal_filters_hexbin_test
 84/107 Test  #87: pdal_filters_sort_test .................   Passed    0.23 sec
        Start  92: pdal_filters_voxel_test
 85/107 Test  #85: pdal_filters_skewness_test .............   Passed    0.29 sec
        Start  93: pdal_filters_voxel_downsize_test
 86/107 Test  #84: pdal_filters_shell_test ................   Passed    0.31 sec
        Start  94: pdal_app_test
 87/107 Test  #91: pdal_filters_hexbin_test ...............   Passed    0.08 sec
        Start  95: pdal_app_plugin_test
 88/107 Test  #88: pdal_filters_splitter_test .............   Passed    0.25 sec
        Start  96: pdal_info_test
 89/107 Test  #92: pdal_filters_voxel_test ................   Passed    0.13 sec
        Start  97: pdal_tile_test
 90/107 Test  #93: pdal_filters_voxel_downsize_test .......   Passed    0.17 sec
        Start  98: pdal_tindex_test
 91/107 Test  #95: pdal_app_plugin_test ...................   Passed    0.16 sec
        Start  99: pdal_merge_test
 92/107 Test  #97: pdal_tile_test .........................   Passed    0.28 sec
        Start 100: pc2pc_test
 93/107 Test  #99: pdal_merge_test ........................   Passed    0.38 sec
        Start 101: hausdorff_test
 94/107 Test  #96: pdal_info_test .........................   Passed    0.71 sec
        Start 102: random_test
 95/107 Test #102: random_test ............................   Passed    0.18 sec
        Start 103: translate_test
 96/107 Test #100: pc2pc_test .............................   Passed    0.65 sec
        Start 104: pdal_io_ilvis2_metadata_test
 97/107 Test #104: pdal_io_ilvis2_metadata_test ...........   Passed    0.08 sec
        Start 105: pdal_io_ilvis2_reader_metadata_test
 98/107 Test  #94: pdal_app_test ..........................   Passed    1.19 sec
        Start 106: xml_schema_test
 99/107 Test #105: pdal_io_ilvis2_reader_metadata_test ....   Passed    0.08 sec
        Start 107: pdal_io_ilvis2_test
100/107 Test  #98: pdal_tindex_test .......................   Passed    1.06 sec
101/107 Test #101: hausdorff_test .........................   Passed    0.68 sec
102/107 Test #106: xml_schema_test ........................   Passed    0.07 sec
103/107 Test #107: pdal_io_ilvis2_test ....................   Passed    0.08 sec
104/107 Test  #78: pdal_filters_pmf_test ..................   Passed    2.05 sec
105/107 Test  #32: pdal_io_ept_reader_test ................   Passed    3.73 sec
106/107 Test  #55: pdal_filters_colorization_test .........   Passed    4.37 sec
107/107 Test #103: translate_test .........................   Passed    2.93 sec

99% tests passed, 1 tests failed out of 107

Total Test time (real) =   7.08 sec

The following tests FAILED:
	 38 - pdal_io_las_writer_test (Failed)
Errors while running CTest
error: Bad exit status from /var/tmp/rpm-tmp.QlX6Zo (%check)
```

With versions:
- proj-devel 6.3.2-5.fc34
- python3-devel 3.9.0-1.fc34
- laszip-devel 3.4.3-3.fc34
- gdal-devel 3.1.3-1.fc34

**Comment by abellgithub** [comment]
This is very strange if it doesn't run consistently. Also, we're running on many platforms where we haven't seen these errors, so I'm not sure how to respond. Sometimes there are errors in the test harness that cause trouble with downstream tests, but these are usually consistent, but it's going to be really hard to figure out what's up without something repeatable when just running a single test at the command line (rather than ctest).

We aren't actively working on 2.1 anymore, and if you're going to build it for release, I would at least pull the 2.1-maintenance branch.

**Comment by neteler** [comment]
I'd be happy to try a single test - if I knew how:

According to https://pdal.io/project/testing.html?highlight=test#running-the-tests
it is

`ctest -V -R pdal_io_bpf_zlib_test`

but

```
ctest -V -R pdal_io_bpf_zlib_test
UpdateCTestConfiguration  from :/root/rpmbuild/BUILD/PDAL-2.1.0-src/test/unit/DartConfiguration.tcl
UpdateCTestConfiguration  from :/root/rpmbuild/BUILD/PDAL-2.1.0-src/test/unit/DartConfiguration.tcl
Test project /root/rpmbuild/BUILD/PDAL-2.1.0-src/test/unit
Constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!
```

Any pointers?

**Comment by abellgithub** [comment]
That command works for me. Perhaps you're not in the proper directory?

Anyway, each test is an executable and it can just be run from the command line. If it's run from the build directory `.\bin\<test_name>`, it should run.

**Comment by neteler** [comment]
I started again today...

`100% tests passed, 0 tests failed out of 107`

Magic. Maybe a dependency got updated?
I'll quickly push it into the Fedora core repo :-)

Closing... thanks for your support anyway, @abellgithub

**Comment by neteler** [comment]
Meanwhile I am trying to package PDAL 2.2.0, this time locally (not in a docker container).

The following two errors appear:
```

 31/113 Test  #31: pdal_io_bpf_zlib_test ..................   Passed    0.43 sec
        Start  35: pdal_io_faux_test
 32/113 Test  #30: pdal_io_bpf_base_test ..................Child aborted***Exception:   0.87 sec
[==========] Running 15 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 15 tests from BpfTestBase
[ RUN      ] BpfTestBase.test_point_major
[       OK ] BpfTestBase.test_point_major (35 ms)
[ RUN      ] BpfTestBase.test_dim_major
[       OK ] BpfTestBase.test_dim_major (18 ms)
[ RUN      ] BpfTestBase.test_byte_major
[       OK ] BpfTestBase.test_byte_major (70 ms)
[ RUN      ] BpfTestBase.roundtrip_byte
[       OK ] BpfTestBase.roundtrip_byte (83 ms)
[ RUN      ] BpfTestBase.roundtrip_dimension
[       OK ] BpfTestBase.roundtrip_dimension (30 ms)
[ RUN      ] BpfTestBase.roundtrip_point
[       OK ] BpfTestBase.roundtrip_point (28 ms)
[ RUN      ] BpfTestBase.roundtrip_scaling
[       OK ] BpfTestBase.roundtrip_scaling (32 ms)
[ RUN      ] BpfTestBase.extra_bytes
(readers.bpf Error) Unsupported BPF version = 0.
/home/mneteler/software/fedora_koji_packages/PDAL/PDAL-2.2.0-src/test/unit/io/BpfSupport.hpp:100: Failure
Expected equality of these values:
  view->size()
    Which is: 0
  506u
    Which is: 506
pdal_io_bpf_base_test: /home/mneteler/software/fedora_koji_packages/PDAL/PDAL-2.2.0-src/pdal/PointView.hpp:469: T pdal::PointView::getFieldAs(pdal::Dimension::Id, pdal::PointId) const [with T = float; pdal::PointId = long unsigned int]: Assertion `pointIndex < m_size' failed.

        Start  36: pdal_io_gdal_reader_test
 33/113 Test  #35: pdal_io_faux_test ......................Child aborted***Exception:   1.26 sec
[==========] Running 10 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 10 tests from FauxReaderTest
[ RUN      ] FauxReaderTest.test_constant_mode_sequential_iter
[       OK ] FauxReaderTest.test_constant_mode_sequential_iter (4 ms)
[ RUN      ] FauxReaderTest.test_random_mode
[       OK ] FauxReaderTest.test_random_mode (3 ms)
[ RUN      ] FauxReaderTest.test_ramp_mode_1
[       OK ] FauxReaderTest.test_ramp_mode_1 (1 ms)
[ RUN      ] FauxReaderTest.test_ramp_mode_2
[       OK ] FauxReaderTest.test_ramp_mode_2 (1 ms)
[ RUN      ] FauxReaderTest.test_return_number
[       OK ] FauxReaderTest.test_return_number (1 ms)
[ RUN      ] FauxReaderTest.one_point
[       OK ] FauxReaderTest.one_point (1 ms)
[ RUN      ] FauxReaderTest.uniform

        Start  37: pdal_io_gdal_writer_test
 34/113 Test  #37: pdal_io_gdal_writer_test ...............   Passed    0.45 sec

...
113/113 Test #109: translate_test .........................   Passed    4.70 sec

98% tests passed, 2 tests failed out of 113

Total Test time (real) =  31.54 sec

The following tests FAILED:
	 30 - pdal_io_bpf_base_test (Child aborted)
	 35 - pdal_io_faux_test (Child aborted)
Errors while running CTest
```

Running them directly:

```
cd PDAL-2.2.0-src/

ctest -V -R pdal_io_bpf_base_test
...
100% tests passed, 0 tests failed out of 1
```

... interestingly no error when run individually.
Does BPF come with a dependency which I need to declare in PDAL.spec?

The other error:

```
ctest -V -R pdal_io_faux_test 
UpdateCTestConfiguration  from :/home/mneteler/software/fedora_koji_packages/PDAL/PDAL-2.2.0-src/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/mneteler/software/fedora_koji_packages/PDAL/PDAL-2.2.0-src/DartConfiguration.tcl
Test project /home/mneteler/software/fedora_koji_packages/PDAL/PDAL-2.2.0-src
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 35
    Start 35: pdal_io_faux_test

35: Test command: /home/mneteler/software/fedora_koji_packages/PDAL/PDAL-2.2.0-src/bin/pdal_io_faux_test
35: Environment variables: 
35:  PDAL_DRIVER_PATH=/home/mneteler/software/fedora_koji_packages/PDAL/PDAL-2.2.0-src/lib64
35: Test timeout computed to be: 10000000
35: [==========] Running 10 tests from 1 test suite.
35: [----------] Global test environment set-up.
35: [----------] 10 tests from FauxReaderTest
35: [ RUN      ] FauxReaderTest.test_constant_mode_sequential_iter
35: [       OK ] FauxReaderTest.test_constant_mode_sequential_iter (3 ms)
35: [ RUN      ] FauxReaderTest.test_random_mode
35: [       OK ] FauxReaderTest.test_random_mode (2 ms)
35: [ RUN      ] FauxReaderTest.test_ramp_mode_1
35: [       OK ] FauxReaderTest.test_ramp_mode_1 (1 ms)
35: [ RUN      ] FauxReaderTest.test_ramp_mode_2
35: [       OK ] FauxReaderTest.test_ramp_mode_2 (1 ms)
35: [ RUN      ] FauxReaderTest.test_return_number
35: [       OK ] FauxReaderTest.test_return_number (0 ms)
35: [ RUN      ] FauxReaderTest.one_point
35: [       OK ] FauxReaderTest.one_point (0 ms)
35: [ RUN      ] FauxReaderTest.uniform
1/1 Test #35: pdal_io_faux_test ................Child aborted***Exception:   0.35 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.36 sec

The following tests FAILED:
	 35 - pdal_io_faux_test (Child aborted)
Errors while running CTest
```

`strace` doesn't show much more:

```
...
read(13, "[       OK ] FauxReaderTest.one_"..., 65536) = 81
write(1, "35: [       OK ] FauxReaderTest."..., 4935: [       OK ] FauxReaderTest.one_point (1 ms)
) = 49
write(1, "35: [ RUN      ] FauxReaderTest."..., 4035: [ RUN      ] FauxReaderTest.uniform
) = 40
epoll_wait(6, [{EPOLLHUP, {u32=13, u64=13}}], 1024, 2147483647) = 1
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_DUMPED, si_pid=1765392, si_uid=1000, si_status=SIGABRT, si_utime=10, si_stime=13} ---
read(7, "*", 1)                         = 1
write(10, "\3106_\2\272U\0\0\21\0\0\0\0\0\0\0", 16) = 16
write(8, "*", 1)                        = 1
rt_sigreturn({mask=[]})                 = 1
read(13, "", 65536)                     = 0
epoll_ctl(6, EPOLL_CTL_DEL, 13, 0x7ffdcb44a70c) = 0
close(13)                               = 0
epoll_wait(6, [{EPOLLIN, {u32=9, u64=9}}], 1024, 2147483647) = 1
read(9, "\3106_\2\272U\0\0\21\0\0\0\0\0\0\0", 512) = 16
wait4(1765392, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGABRT && WCOREDUMP(s)}], WNOHANG, NULL) = 1765392
write(3, "35/113 Testing: pdal_io_faux_tes"..., 34) = 34
write(3, "35/113 Test: pdal_io_faux_test\n", 31) = 31
...
```

My system:

```
uname -a
Linux oboe 5.6.16-300.fc32.x86_64 #1 SMP Thu Jun 4 18:08:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 32 (Thirty Two)
...
```

**Comment by abellgithub** [comment]
This is strange and I think we'll need either a good traceback or a docker container with your environment (without PDAL) that would let us test.

**Comment by neteler** [comment]
Please let me know how to create a better than above traceback. I'm not really familiar with cmake.

Re: docker environment, see above https://github.com/PDAL/PDAL/issues/3261#issuecomment-708520016

**Comment by abellgithub** [comment]
Run the program in a debugger (gdb/lldb). When the program halts, use the "bt" command.

**Comment by neteler** [comment]
OK, I had to tell it to not detach ("Detaching after fork from child process"), still not halting:

```
gdb /usr/bin/ctest
set follow-fork-mode child
r
...
 34/113 Test  #34: pdal_io_ept_addon_writer_test ..........   Passed    4.05 sec
        Start  35: pdal_io_faux_test
 35/113 Test  #35: pdal_io_faux_test ......................Child aborted***Exception:   0.31 sec
        Start  36: pdal_io_gdal_reader_test
 36/113 Test  #36: pdal_io_gdal_reader_test ...............   Passed    0.78 sec
...
113/113 Test #113: pdal_io_ilvis2_test ....................   Passed    0.13 sec

99% tests passed, 1 tests failed out of 113

Total Test time (real) =  60.17 sec

The following tests FAILED:
	 35 - pdal_io_faux_test (Child aborted)
Errors while running CTest

(gdb) bt
No stack.
```

A bit tricky... 
This happens when building with the [SPEC](https://src.fedoraproject.org/rpms/PDAL/blob/master/f/PDAL.spec) file.

When running the tests locally, then no error occurs.

**Comment by abellgithub** [comment]
I tried to get things to build on fedora:34 docker container and failed. It seems significantly different from other distributions. I'm sure that I can get this to work, but it would take time and I'm not sure it's something we're going to bite off. The failures you're seeing don't seem like PDAL issues, exactly, but general issues with the way the application is linked or dependencies or something. Maybe it's not ready for prime-time yet? The version of cmake that gets downloaded by `dnf` won't find the `gdal` that's installed by `dnf`.  These kind of things can be solved, but we don't normally get involved with pre-release operating systems.

**Comment by neteler** [comment]
Thanks for trying and sorry it failed for you (here it worked but maybe it is indeed still unstable).
It's ok for me to leave this issue for now. Maybe in some months just runs ok...?

**Comment by abellgithub** [comment]
I'm skeptical that any of this is a PDAL problem, but if you want to pursue, you can run a failing test in the debugger to see where it dies (don't run ctest in the debugger).

I also tried to install dependencies via conda and that failed as well. The conda packages require libnsl.so.1, but fedora 34 provides only libnsl.so.2.  This seems to be a common issue with RedHat/Fedora, but I don't know the path to resolution.

**Comment by neteler** [comment]
> I'm skeptical that any of this is a PDAL problem, but if you want to pursue, you can run a failing test in the debugger to see where it dies (don't run ctest in the debugger).

While I am just a volunteer with the packaging, I don't like to easily give up. Of course I don't want to waste your time.

My only problem is that I don't get how to run a PDAL test without ctest. Any pointer to documentation/howto would be welcome.

**Comment by abellgithub** [comment]
The tests are executables. They are in the `bin` directory.  If your process directory is the cmake build directory, you can run any test by just running them: `.\bin\<test name>`.

**Comment by neteler** [comment]
Thanks.
I have reported the problems upstream: https://bugzilla.redhat.com/show_bug.cgi?id=1893566

**Comment by neteler** [comment]
A bugfix has been applied to PDAL in Fedora (thanks to @manisandro), see also #3280 

(full change: https://src.fedoraproject.org/rpms/PDAL/c/be5574fc7674385eddcac263401dace724552a94?branch=master)

This fixes the compilation of PDAL 2.2.0.

**Comment by manisandro** [comment]
Actually I just realized that I accidentally left the %ctest commented out, not sure whether this segfault here is really fixed. I'll investigate more.

**Comment by manisandro** [comment]
So apparently running ctest in parallel can trigger failures such as the pdal_filters_overlay_test test failing with

    "Unable to open stream for '/builddir/build/BUILD/PDAL-2.2.0-src/test/data/../temp/temp.laz' with error 'No such file or directory'"

Possibly multiple tests trying to operate on the same file in parallel? Switching to running ctest serially works, so as far as the Fedora package is concerned problem solved.
