### ISSUE TITLE
SegFault in LAS reader

### ISSUE THREAD

**Issue by bacek** [PDAL/PDAL#3274]
LAS reader is segfaulting when non-existing extra dimensions are specified and actual file doesn't have it.

PDAL is build from `2.2-maintenance` branch:

```
./bin/pdal -v 4 translate --readers.las.extra_dims=Foo=int8 t.laz out.laz
(PDAL Debug) Debugging...
(pdal translate Debug) Executing pipeline in stream mode.
Segmentation fault

```

**Expected behaviour**
Do not crash.

**System/installation information:**
Please provide information on your PDAL version (`pdal --version`) and system (e.g., `uname -a` or `ver`).

```
$ uname -a
Linux hp 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ pdal --version
pdal 2.2.0 (git-version: ad3166)

```

Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
pdal::LeExtractor::operator>> (this=0x7fffffffd1c0, v=@0x7fffffffd0e0: 0 '\000') at ../pdal/util/Extractor.hpp:227
227	        v = *(const int8_t *)m_gptr++;
(gdb) bt
#0  pdal::LeExtractor::operator>> (this=0x7fffffffd1c0, v=@0x7fffffffd0e0: 0 '\000') at ../pdal/util/Extractor.hpp:227
#1  0x00007ffff79876d7 in pdal::Utils::extractDim<pdal::LeExtractor> (ext=..., type=pdal::Dimension::Type::Signed8) at ../pdal/PDALUtils.hpp:130
#2  0x00007ffff79804a8 in pdal::LasReader::loadExtraDims (this=0x555555695c80, istream=..., point=...) at ../io/LasReader.cpp:954
#3  0x00007ffff797f63a in pdal::LasReader::loadPointV10 (this=0x555555695c80, point=..., p=...) at ../io/LasReader.cpp:759
#4  0x00007ffff797f25c in pdal::LasReader::loadPoint (this=0x555555695c80, point=..., p=...) at ../io/LasReader.cpp:708
#5  0x00007ffff797ea12 in pdal::LasReader::processOne (this=0x555555695c80, point=...) at ../io/LasReader.cpp:589
#6  0x00007ffff7b0ac52 in pdal::Streamable::execute (this=0x555555696770, table=..., stages=std::__cxx11::list = {...}, srsMap=std::map with 0 elements) at ../pdal/Streamable.cpp:221
#7  0x00007ffff7b0a6cd in pdal::Streamable::execute (this=0x555555696770, table=...) at ../pdal/Streamable.cpp:155
#8  0x00007ffff7ab173a in pdal::PipelineManager::execute (this=0x555555692e38, mode=pdal::ExecMode::PreferStream) at ../pdal/PipelineManager.cpp:242
#9  0x00007ffff7a6ee21 in pdal::TranslateKernel::execute (this=0x555555692e20) at ../kernels/TranslateKernel.cpp:226
#10 0x00007ffff7a9c2ad in pdal::Kernel::innerRun (this=0x555555692e20, args=...) at ../pdal/Kernel.cpp:283
#11 0x00007ffff7a9c01c in pdal::Kernel::doExecution (this=0x555555692e20, args=...) at ../pdal/Kernel.cpp:247
#12 0x00007ffff7a9be8e in pdal::Kernel::run (this=0x555555692e20, cmdArgs=std::vector of length 3, capacity 4 = {...}, log=std::shared_ptr<pdal::Log> (use count 9, weak count 0) = {...}) at ../pdal/Kernel.cpp:235
#13 0x00005555555ca30d in App::execute (this=0x7fffffffda10, cmdArgs=std::vector of length 3, capacity 4 = {...}, log=std::shared_ptr<pdal::Log> (use count 9, weak count 0) = {...}) at ../apps/pdal.cpp:366
#14 0x00005555555c9da2 in main (argc=7, argv=0x7fffffffdba8) at ../apps/pdal.cpp:310
(gdb) 
```

`LasReader::loadExtraDims` is using `extra_bytes` which is `null`.

```
#3  0x00007ffff797f63a in pdal::LasReader::loadPointV10 (this=0x555555695c80, point=..., p=...) at ../io/LasReader.cpp:759
759	        loadExtraDims(extractor, point);
(gdb) l
754	    }
755	
756	    if (m_extraDims.size())
757	    {
758	        LeExtractor extractor((const char *)p.extra_bytes, p.num_extra_bytes);
759	        loadExtraDims(extractor, point);
760	    }
761	}
762	#endif // PDAL_HAVE_LASZIP
763	
(gdb) p p.extra_bytes
$12 = (laszip_U8 *) 0x0

```

 `LeExtractor` doesn't have any internal checks on pointers validity:

```
#1  0x00007ffff79876d7 in pdal::Utils::extractDim<pdal::LeExtractor> (ext=..., type=pdal::Dimension::Type::Signed8) at ../pdal/PDALUtils.hpp:130
130	            ext >> e.s8;
(gdb) 
#0  pdal::LeExtractor::operator>> (this=0x7fffffffd1c0, v=@0x7fffffffd0e0: 0 '\000') at ../pdal/util/Extractor.hpp:227
227	        v = *(const int8_t *)m_gptr++;
(gdb) p *this
$13 = {<pdal::Extractor> = {_vptr.Extractor = 0x7ffff7f60038 <vtable for pdal::LeExtractor+16>, m_eback = 0x0, m_egptr = 0x0, m_gptr = 0x1 <error: Cannot access memory at address 0x1>}, <No data fields>}
```

**Comment by bacek** [comment]
Zipped test.laz to reproduce issue easier.

[test.zip](https://github.com/PDAL/PDAL/files/5427431/test.zip)
