### ISSUE TITLE
PyCharm 2020.3 fails to install PDAL in venv

### ISSUE THREAD

**Issue by roncapat** [PDAL/PDAL#3309]
Whenever I try to install in:

Ubuntu 20.04
PyCharm Professional 2020.3
Venv Python 3.8

PDAL version 2.3.5, I get this error:

```
Collecting PDAL==2.3.5
  Using cached PDAL-2.3.5.tar.gz (945 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Building wheels for collected packages: PDAL
  Building wheel for PDAL (PEP 517): started
  Building wheel for PDAL (PEP 517): finished with status 'error'
Failed to build PDAL

  ERROR: Command errored out with exit status 1:
   command: /home/patrick/O2D/venv/bin/python /home/patrick/O2D/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpuwecb60q
       cwd: /tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5
  Complete output (89 lines):
  
  
  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 9.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 9.3.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - success
  --------------------------------------------------------------------------------
  
  Configuring Project
    Working directory:
      /tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5/_skbuild/linux-x86_64-3.8/cmake-build
    Command:
      cmake /tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5/pdal -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/patrick/O2D/venv/bin/python -DPYTHON_VERSION_STRING:STRING=3.8.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-k8_lntws/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
  
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Python3: /home/patrick/PycharmProjects/O2D/venv/bin/python3.8 (found version "3.8.5") found components: Interpreter Development NumPy Development.Module Development.Embed
  CMake Error at CMakeLists.txt:21 (find_package):
    By not providing "FindPDAL.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "PDAL", but
    CMake did not find one.
  
    Could not find a package configuration file provided by "PDAL" (requested
    version 2.1) with any of the following names:
  
      PDALConfig.cmake
      pdal-config.cmake
  
    Add the installation prefix of "PDAL" to CMAKE_PREFIX_PATH or set
    "PDAL_DIR" to a directory containing one of the above files.  If "PDAL"
    provides a separate development package or SDK, be sure it has been
    installed.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5/_skbuild/linux-x86_64-3.8/cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "/tmp/pip-build-env-k8_lntws/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 582, in setup
      env = cmkr.configure(cmake_args,
    File "/tmp/pip-build-env-k8_lntws/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 229, in configure
      raise SKBuildError(
  
  An error occurred while configuring with CMake.
    Command:
      cmake /tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5/pdal -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5/_skbuild/linux-x86_64-3.8/cmake-install -DPYTHON_EXECUTABLE:FILEPATH=/home/patrick/O2D/venv/bin/python -DPYTHON_VERSION_STRING:STRING=3.8.5 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.8.so -DSKBUILD:BOOL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-k8_lntws/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
      /tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5/pdal
    Working directory:
      /tmp/pip-install-6ysmcj9q/pdal_d6ea27e3a46a43b5aa0ae704a9f811b5/_skbuild/linux-x86_64-3.8/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for PDAL
ERROR: Could not build wheels for PDAL which use PEP 517 and cannot be installed directly

```

**Comment by hobu** [comment]
`pip install PDAL` is going to get you the [PDAL Python bindings](https://github.com/PDAL/python/), not the PDAL library. The Python bindings require the base PDAL library. One way to install this is via Conda Forge.
