### ISSUE TITLE
segfault parsing pipeline

### ISSUE THREAD

**Issue by strk** [PDAL/PDAL#822]
The XML lacks some possibly required fields, but that shouldn't segfault.
Backtrace:
```
#0  0x000000000041ec58 in std::_Rb_tree<std::string, std::pair<std::string const, pdal::Option>, std::_Select1st<std::pair<std::string const, pdal::Option> >, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > >::_M_begin() ()
(gdb) bt
#0  0x000000000041ec58 in std::_Rb_tree<std::string, std::pair<std::string const, pdal::Option>, std::_Select1st<std::pair<std::string const, pdal::Option> >, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > >::_M_begin() ()
#1  0x00007f88443c1841 in std::_Rb_tree<std::string, std::pair<std::string const, pdal::Option>, std::_Select1st<std::pair<std::string const, pdal::Option> >, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > >::clear() () from /usr/local/lib/libpdalcpp.so
#2  0x00007f88443bd9a5 in std::_Rb_tree<std::string, std::pair<std::string const, pdal::Option>, std::_Select1st<std::pair<std::string const, pdal::Option> >, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > >::operator=(std::_Rb_tree<std::string, std::pair<std::string const, pdal::Option>, std::_Select1st<std::pair<std::string const, pdal::Option> >, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > > const&) () from /usr/local/lib/libpdalcpp.so
#3  0x00007f88443baca9 in std::multimap<std::string, pdal::Option, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > >::operator=(std::multimap<std::string, pdal::Option, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > > const&) () from /usr/local/lib/libpdalcpp.so
#4  0x00007f88443b9355 in pdal::Options::operator=(pdal::Options const&) () from /usr/local/lib/libpdalcpp.so
#5  0x00007f88443b9383 in pdal::Stage::setOptions(pdal::Options) () from /usr/local/lib/libpdalcpp.so
#6  0x00007f88443e982b in pdal::PipelineReader::parseElement_Filter(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) () from /usr/local/lib/libpdalcpp.so
#7  0x00007f88443e8e03 in pdal::PipelineReader::parseElement_anystage(std::string const&, boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) () from /usr/local/lib/libpdalcpp.so
#8  0x00007f88443e967c in pdal::PipelineReader::parseElement_Filter(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) () from /usr/local/lib/libpdalcpp.so
#9  0x00007f88443e8e03 in pdal::PipelineReader::parseElement_anystage(std::string const&, boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) () from /usr/local/lib/libpdalcpp.so
#10 0x00007f88443e9e6a in pdal::PipelineReader::parseElement_Writer(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) () from /usr/local/lib/libpdalcpp.so
#11 0x00007f88443ea499 in pdal::PipelineReader::parseElement_Pipeline(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) () from /usr/local/lib/libpdalcpp.so
#12 0x00007f88443ea8d8 in pdal::PipelineReader::readPipeline(std::istream&) () from /usr/local/lib/libpdalcpp.so
#13 0x00007f88443eaa2c in pdal::PipelineReader::readPipeline(std::string const&) () from /usr/local/lib/libpdalcpp.so
#14 0x00007f88444d15bb in pdal::PipelineKernel::execute() () from /usr/local/lib/libpdalcpp.so
#15 0x00007f88443b55a7 in pdal::Kernel::innerRun() () from /usr/local/lib/libpdalcpp.so
#16 0x00007f88443b45b9 in pdal::Kernel::do_execution() () from /usr/local/lib/libpdalcpp.so
#17 0x00007f88443b4a60 in pdal::Kernel::run(int, char const**, std::string const&) () from /usr/local/lib/libpdalcpp.so
#18 0x000000000041c392 in main ()
```

Pipeline:
```
<?xml version="1.0" encoding="utf-8"?>
<Pipeline version="1.0">
    <Writer type="writers.pgpointcloud">
<!--
        <Option name="connection">host='localhost' dbname='pc' user='lidar'</Option>
-->
        <Option name="table">20h64_1x1_dsm_004_2010</Option>
        <Option name="srid">3003</Option>
        <Filter type="filters.chipper">
            <Option name="capacity">600</Option>
            <Filter type="filters.cache">
                <Reader type="readers.las">
                    <Option name="filename">20h64_1x1_dsm_004_2010_3003.las</Option>
<!--
                    <Option name="spatialreference">EPSG:26910</Option>
-->
                </Reader>
            </Filter>
        </Filter>
    </Writer>
</Pipeline>
```

**Comment by strk** [comment]
And a valgrind report:
```
==8912== Invalid read of size 8
==8912==    at 0x41EC58: std::_Rb_tree<std::string, std::pair<std::string const, pdal::Option>, std::_Select1st<std::pair<std::string const, pdal::Option> >, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > >::_M_begin() (in /usr/local/bin/pdal)
==8912==    by 0x50D9840: std::_Rb_tree<std::string, std::pair<std::string const, pdal::Option>, std::_Select1st<std::pair<std::string const, pdal::Option> >, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > >::clear() (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x50D59A4: std::_Rb_tree<std::string, std::pair<std::string const, pdal::Option>, std::_Select1st<std::pair<std::string const, pdal::Option> >, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > >::operator=(std::_Rb_tree<std::string, std::pair<std::string const, pdal::Option>, std::_Select1st<std::pair<std::string const, pdal::Option> >, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > > const&) (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x50D2CA8: std::multimap<std::string, pdal::Option, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > >::operator=(std::multimap<std::string, pdal::Option, std::less<std::string>, std::allocator<std::pair<std::string const, pdal::Option> > > const&) (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x50D1354: pdal::Options::operator=(pdal::Options const&) (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x50D1382: pdal::Stage::setOptions(pdal::Options) (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x510182A: pdal::PipelineReader::parseElement_Filter(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x5100E02: pdal::PipelineReader::parseElement_anystage(std::string const&, boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x510167B: pdal::PipelineReader::parseElement_Filter(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x5100E02: pdal::PipelineReader::parseElement_anystage(std::string const&, boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x5101E69: pdal::PipelineReader::parseElement_Writer(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) (in /usr/local/lib/libpdalcpp.so)
==8912==    by 0x5102498: pdal::PipelineReader::parseElement_Pipeline(boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string> > const&) (in /usr/local/lib/libpdalcpp.so)
==8912==  Address 0x20 is not stack'd, malloc'd or (recently) free'd
```
